title: My New Hugo Site
theme: test
baseURL: https://t-kemmochi.github.io/hugo-theme-actions/

defaultContentLanguage: ja
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
removePathAccents: true

languages: 
  ja: 
    languageCode: ja
    languageName: 日本語
    title: T. Kemmochi
    weight: 1
    menus:
      main:
        - name: Home
          pageRef: /
          weight: 10
        - name: Posts
          pageRef: /posts
          weight: 20
  en: 
    languageCode: en-us
    languageName: English
    title: T. Kemmochi
    weight: 2
    menus:
      main:
        - name: Home
          pageRef: /
          weight: 10
        - name: Posts
          pageRef: /posts
          weight: 20
  zh: 
    languageCode: zh
    languageName: ZH
    title: Chinese
    weight: 3

