title: My New Hugo Site
theme: test
baseURL: https://t-kemmochi.github.io/hugo-theme-actions/

defaultContentLanguage: ja
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
removePathAccents: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: emacs
    tabWidth: 4