ja: 
  languageCode: ja
  languageName: 日本語
  title: T. Kemmochi
  weight: 1
  menus:
    main:
      - name: Home
        pageRef: /
        weight: 10
      - name: CV
        pageRef: /cv
        weight: 20
      - name: Research
        pageRef: /research
        weight: 30
      - name: Publications
        pageRef: /publications
        weight: 40
      - name: Talks
        pageRef: /talks
        weight: 50
      - name: Memo
        pageRef: /memo
        weight: 70
en: 
  languageCode: en-us
  languageName: English
  title: T. Kemmochi
  weight: 2
  menus:
    main:
      - name: Home
        pageRef: /
        weight: 10
      - name: CV
        pageRef: /cv
        weight: 20
      - name: Research
        pageRef: /research
        weight: 30
      - name: Publications
        pageRef: /publications
        weight: 40
      - name: Talks
        pageRef: /talks
        weight: 50
      - name: Memo
        pageRef: /memo
        weight: 70